#!/usr/bin/env python

import os, sys
from contextlib import closing
import re
import zipfile

def scan_file(pattern, path):
  if zipfile.is_zipfile(path):
    with closing(zipfile.ZipFile(path)) as zf:
      for name in zf.namelist():
        if re.search(pattern, name):
          print "%s: %s" % (path, name)

def scan_zip_files(pattern, path):
  if os.path.isfile(path):
    scan_file(pattern, path)
  else:
    for here, dirs, files in os.walk(path):
      for f in (os.path.join(here, f) for f in files):
        scan_file(pattern, f)

if __name__ == '__main__':
  if len(sys.argv) < 3:
    print >>sys.stderr, "Usage: %s pattern path..." % sys.argv[0]
    sys.exit(1)

  pattern = sys.argv[1]
  scanned, total = 0, 0
  for path in sys.argv[2:]:
    scan_zip_files(pattern, path)
